### ISSUE TITLE
Request 1.18.2

### ISSUE THREAD

**Issue by DEEP-IOS** [NullD4201/ReplayMod-Forge-Reborn-1201#1]
Can you please provide an update for version 1.18.2 or share a link to download this specific version? This is crucial for me. Thank you.

**Comment by NullD4201** [comment]
I've just uploaded my development code for 1.20.1. I was working on it but could not make this work.
Sorry for the inconvenience. Maybe late of this year I might update for version 1.18.2 instead of 1.20.1.
